name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the project dependencies
        run: make install-dev
      - name: Run lint
        run: |
          make lint-check
      - name: Run tests
        run: |
          make test