name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-laest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install the project dependencies
        run: make install-dev
      - name: Run lint
        run: |
          make lint-check
      - name: Run tests
        run: |
          make tests