name: Release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install pypa/build
        run: pip install build --user
      - name: Install the project dependencies
        run: make install
      - name: Build wheel and tarball
        run: python -m build . --outdir dist/
  
  pypi-publish:
    name: Publish to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write 
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1